# Terminal colors
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ',xterm-ghostty:RGB,wezterm:RGB,xterm-kitty:RGB,xterm-256color:RGB'
set -sa terminal-features ",xterm-ghostty*:RGB,wezterm*:RGB,alacritty*:RGB,foot*:RGB,xterm-kitty*:RGB,xterm-256color:RGB"

# Global settings 
set -g mouse on
set -g history-limit 64096
set -sg escape-time 0
set -g focus-events on
set -g status-keys vi
setw -g mode-keys vi

## Window and pane index
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# Remap prefix
unbind C-b
set -g prefix C-t
bind-key C-t send-prefix
bind-key C-y send-prefix

# Reload config
bind r { source-file ~/.config/tmux/tmux.conf; display-message "Config Reloaded." }

# Split windows
bind v split-window -h -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'

# Moving window
bind -r C-p { swap-window -t -1; previous-window }
bind -r C-n { swap-window -t +1; next-window }

# Move pane in directions
# bind -T root -r H swap-pane -t {left-of}  \; select-pane -t {left-of}
# bind -T root -r J swap-pane -t {down-of}  \; select-pane -t {down-of}
# bind -T root -r K swap-pane -t {up-of}    \; select-pane -t {up-of}
# bind -T root -r L swap-pane -t {right-of} \; select-pane -t {right-of}

# Bottom pane toggleable
unbind \;
bind \; if -F '#{==:#{window_panes},1}' \
    { split-window -v -c '#{pane_current_path}' } \
    { if -F '#{pane_at_top}' { select-pane -D } {select-pane -U; resize-pane -Z} }

# Move pane to new prev/next window
bind o if -F '#{e|>:#{window_panes},1}' { break-pane -a }
bind i if -F '#{e|>:#{window_panes},1}' { break-pane -b }

# Move pane to prev/next window
bind -r > if -F '#{>=:#{session_windows},1}' { join-pane -t:+1 }
bind -r < if -F '#{>=:#{session_windows},1}' { join-pane -t:-1 }

# Enter copy-mode
unbind space
bind space copy-mode

# Session
unbind c
bind c new-session
bind D detach

# Paste content in current pane
bind C paste-buffer

# Pane switching (vim-like)
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Resizing pane (vim-like)
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-h resize-pane -L 2
bind -r C-l resize-pane -R 2

# Toggle zoom
bind z resize-pane -Z 

# Vim-like visual mode
bind -T copy-mode-vi v send-keys -X begin-selection

# clipboard linux or macos
if-shell "uname -s | grep -q Darwin" "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \"reattach-to-user-namespace pbcopy\""
if-shell "uname -s | grep -q Linux" "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \"xclip -i -f -selection primary | xclip -i -selection clipboard\""

# New window
unbind t
bind t new-window

# status bar
set -g status on
set -g status-interval 2
set -g status-bg "#1e1e2e"
set -g status-fg "#6C7086"
set -g status-left-length 20

set -g status-left "#[fg=blue,bold] ● #S #[default] "

set -g window-status-separator "  "
set -g window-status-current-style "fg=#9399B2,bold"
set -g status-right ""

# vim: set filetype=tmux :
