export GUM_CHOOSE_SELECTED_PREFIX="[x] "
export GUM_CHOOSE_UNSELECTED_PREFIX="[ ] "
export GUM_CHOOSE_CURSOR_PREFIX="[ ] "

export GUM_FILTER_SELECTED_PREFIX="[x] "
export GUM_FILTER_UNSELECTED_PREFIX="[ ] "
export GUM_FILTER_CURSOR_PREFIX="[ ] "
export GUM_FILTER_INDICATOR="> "

export GUM_INPUT_PROMPT="> "
